### ISSUE TITLE
Is claiming land possible?

### ISSUE THREAD

**Issue by alexp10** [codehz/ElementZero#100]
hi, does any ability to claim land exist with ElementZero?

Thanks
Alex

**Comment by Weissnix4711** [comment]
Yeah, making such a plugin is possible.

No one has made it work well (as far as I know). There have been attempts at making such a thing using the scripting API. I remember a while back, someone posted some screenshots on the Telegram.

The ideal method would really be to make a plugin. I'm not going to myself, because I'm not too good with C++, and don't have the time right now. I will leave this issue open, in case anyone else would like to have a shot at making the plugin.

**Comment by Weissnix4711** [comment]
Check out [Extollite's land manager mod](https://github.com/Extollite/LandManager).

As with most mods, it's still in development, although it's a good starting point if you would like to make any edits yourself.
