### ISSUE TITLE
A better plugin library/database

### ISSUE THREAD

**Issue by elijahr2411** [codehz/ElementZero#101]
As of now, the only plugin "Library" for ElementZero is an always open GitHub issue. However, for several reasons, this is inefficient. You can probably understand why, but I'll put some reasons below.

- Unorganized
- Hard to search through
- Can be spammed.

As such, I suggest something (probably a website) for plugin submissions. One viable (In my opinion) option is to setup a forum like [Free Flarum](https://www.freeflarum.com/), a free forum hosting focused on small open-source communities, and Mod devs could post GitHub links there. However, anything would work, and someone could even setup something more advanced like [Adventure](https://github.com/WinWorldPC/adventure). I feel like this would greatly assist in development of ElementZero.

**Comment by Weissnix4711** [comment]
This.

The current situation is a failure. I mean sure, I made a scraper in python in maybe 5 minutes. Some simple regex to grab data from the issue. And that worked, but it ain't ideal. At all.

But the problem is that most of us here don't have a clue about how to set up what you just mentioned. So hey, if you want to help set something up, please do. :)

**Comment by elijahr2411** [comment]
@Weissnix4711 I'm happy you agree. I'd be happy to set this up, but the problem is that I have no idea where I'd link it to make it noticeable by Plugin Devs. If you have any idea where I'd put a link, please tell me. Thanks!

**Comment by madeofstown** [comment]
I support this idea 100%! I think someone more closely tied to the project needs to get the ball rolling (register the forum) but I can definitely help moderate and answer questions.

**Comment by elijahr2411** [comment]
@randommouse Yeah, I feel the same way. I'd be happy to help set it up and moderate, but someone running the project would have to maybe add it to the README to get people to notice it and post their plugins.

**Comment by madeofstown** [comment]
> @Weissnix4711 I'm happy you agree. I'd be happy to set this up, but the problem is that I have no idea where I'd link it to make it noticeable by Plugin Devs. If you have any idea where I'd put a link, please tell me. Thanks!

They have a Telegram channel @ https://t.me/ezloader

**Comment by elijahr2411** [comment]
> They have a Telegram channel @ https://t.me/ezloader

Seems pretty inactive. No posts since May.

**Comment by Weissnix4711** [comment]
> They have a Telegram channel @ https://t.me/ezloader

That's the one I meant, yes.

> @Weissnix4711 I'm happy you agree. I'd be happy to set this up, but the problem is that I have no idea where I'd link it to make it noticeable by Plugin Devs. If you have any idea where I'd put a link, please tell me. Thanks!

I can add it to the wiki if you like. I'm working on the wiki anyway. We need better mod creation documentation.

**Comment by Weissnix4711** [comment]
> > They have a Telegram channel @ https://t.me/ezloader
> 
> Seems pretty inactive. No posts since May.

Click the discuss button at the bottom. It'll bring up another chat.

**Comment by elijahr2411** [comment]
I'd prefer to get approval from someone managing the project first before I just link something to the official thread. Problem is I don't know who to ask.

**Comment by Weissnix4711** [comment]
I'm sure it's going to be fine. Btw, @codehz is the creator and main developer of this entire project.

**Comment by elijahr2411** [comment]
@codehz Are you okay with this? Just wanted to get your feedback before setting this all up. You can register it yourself if you want or I can do it and set you (And anyone) as an admin. Thanks

**Comment by elijahr2411** [comment]
I setup something so people can see what it looks like. https://elementzero.flarum.cloud/
I'd prefer if @codehz approves before someone adds it to the wiki or readme or anything.

**Comment by lightyisreal** [comment]
> I setup something so people can see what it looks like. https://elementzero.flarum.cloud/
> I'd prefer if @codehz approves before someone adds it to the wiki or readme or anything.

The website is so good, i hope @codehz can use it

**Comment by Weissnix4711** [comment]
> I setup something so people can see what it looks like. https://elementzero.flarum.cloud/
> I'd prefer if @codehz approves before someone adds it to the wiki or readme or anything.

Is it possible to have sub categories in Flarum? Or some sort of tags? I suppose adding [TAG] to the title is possible, but isn't ideal. It would make searching through posts nearly impossible.

Also, people would need to upload their mods to a seperate site, then post the link in the forum. Hosting the files directly on the site would be ideal, because all the download links would be the same. Eg: `www.website.com/<mod-name>/download.zip`

I'm not sure if there is a service out there that does this sort of thing. Otherwise we would need to make our own software to do this, and hosting would be expensive too...

**Comment by elijahr2411** [comment]
@Weissnix4711
I was thinking that the easiest way would just be to link to a github repo. That's actually how Poggit does it, but automated.

I added some categories, but flarum made it kinda difficult because its replacing the text in the tag settings with placeholders (Similar to what ElementZero does without dictionary.) I emailed their support about it, but for now I'll just work with it.

**Comment by Weissnix4711** [comment]
@elijahr2411 I've been messing around, and have just set up my own Free Flarum site.

There's a few things I noticed. First off, a few extensions I thought were kind of neat.

- Can we enable nicknames? After signing up through whichever method you prefer, you can't change your name.
- Private discussions. Not everyone uses the telegram, or has their email on their Github. Private messages are just really useful to have.
- Google login. For easy login. In case people don't wish to use GitHub / email.
- Disable "likes" and enable "gamification". That way, people can upvote / downvote mods, instead of just liking.

I've also been messing with the appearance and stuff. A custom footer with links to the GitHub page might be helpful. Or even something similar to the footer on our current [wiki](https://github.com/Element-0/ElementZero/wiki), with build, release, and telegram links.

**Comment by elijahr2411** [comment]
@Weissnix4711 I enabled nicknames and private discussions. I didnt do Google login because my google account won't let me make an app for some reason. I did gamification and also added Wood, Stone, Iron, Diamond, and Netherrite ranks to it. I also did a footer with links to the github and issues pages.

**Comment by a-person-01001001** [comment]
this would be nice, especially since i'm working on a mod rn. Maybe we could have like documentation for mod making. Like python or c++ has docs. Like what everything in EZ's files does? :/

**Comment by Weissnix4711** [comment]
> documentation for mod making

The wiki page for that exists, but it's still a WIP. I think the best method right now would be to have a look at other people's mods (including the built-in ones) and also use [MinimalModTemplate](https://github.com/Element-0/MinimalModTemplate) as a starting point.

**Comment by Weissnix4711** [comment]
@elijahr2411 Please check your private messages on the Flarum. I do not know whether you have received a notification or not, hence why I am posting here.

Also, sorry to the rest of you who I may have just pinged.

**Comment by elijahr2411** [comment]
@Weissnix4711 Could you please add the forum to the wiki, or maybe even the README? Thanks!
(And make sure you state that it's not official!) (yet)

**Comment by Weissnix4711** [comment]
It is in the wiki already.

If you want to add it to the readme, make a pr. That's up to CodeHz.

**Comment by elijahr2411** [comment]
Ah. Thanks.



Sent from my toaster oven



-------- Original message --------

**Comment by elijahr2411** [comment]
I'm gonna close this. Not very relevant anymore.
