### ISSUE TITLE
Anti TP Mod

### ISSUE THREAD

**Issue by a-person-01001001** [codehz/ElementZero#110]
Hello. I'm trying to make an anti-teleport mod for a server. I don't really know how to do this, so help would be appreciated :). This is also my first mod, don't know if I took up too large of a project.

The mod is supposed to work like this: If a player who is not opped moves >500 blocks and is not changing dimensions, teleport them back to their original position. Help would be appreciated. Thank you :).

**Comment by codehz** [comment]
@a-person-01001001 You can turn on the builtin movement correct

**Comment by a-person-01001001** [comment]
I can turn on "`server-authoritative-movement`" in server.properties if that's what you're talking about.
oops 20 seconds later I realize you mean "`correct-player-movement`" Yes I can turn that on.

**Comment by a-person-01001001** [comment]
They both don't do anything with a hacker using a command like .tp :/.

**Comment by Weissnix4711** [comment]
Yeah, that's an issue.

I'm not sure if @Extollite 's anti-cheat manages to block TP hacks. It may do.

Aside from that, you can hope that this gets fixed by Mojang, ~~or if you know a thing or two about C++, and want to try, you can always improve the anti-cheat and make a pull-request.~~ Didn't read your first comment properly.

It might take a while for Basic Anticheat to support this, because there are not that many developers working on it.

As far as mod development goes, the best resource is to look at all the other mods. There is also [a template](https://github.com/Element-0/MinimalModTemplate) you could use.

The [wiki page on mod development](https://github.com/Element-0/ElementZero/wiki/How-to-create-a-custom-mod) is still a work in progress, I'm afraid.

**Comment by Weissnix4711** [comment]
Sorry about closing the issue, didn't mean to do that.

**Comment by nickg2** [comment]
if you are looking for one, https://elementzero.flarum.cloud/d/18-nac-nicks-anticheat
