### ISSUE TITLE
A much needed feature

### ISSUE THREAD

**Issue by CvldYT** [codehz/ElementZero#116]
Add a command called 'restart' that runs the following commands in the console

save hold
save resume
stop

Then have the server open again.

This seems to help clear lots of lag and buildup.

**Comment by Weissnix4711** [comment]
The stop command saves everything itself.

As for restarting the server, there's a number of things you can do. Provided you are running this with docker, you can add the `--restart=blah` flag to your docker run command. Replace `blah` with [any of these options](https://docs.docker.com/engine/reference/run/#restart-policies---restart) depending on what circumstances you would like to restart the container in.

If you stopped the container manually (with `docker stop <container_name>`), you can also restart the container with `docker restart <container_name>`). Note: you must run the server first, without the `--rm` flag, otherwise this method will not work. The remove flag will auto delete your container after you stop it, so it cannot be restarted.
