### ISSUE TITLE
1.16 server interface missing???

### ISSUE THREAD

**Issue by Talark-Systems** [codehz/ElementZero#120]
When I run the docker command, nothing happens:
~~~
sudo docker run --rm -ti -p 19132:19132/udp -v ~/path/to/server/:/data codehz/wine:bdlauncher-runtime

user@computer:~/path/to/server$
~~~

How can I run commands on my server now/see players joining?

**Comment by Weissnix4711** [comment]
Your container seems to be stopping immediately. Docker containers automatically stop when the main process (EZ in this case) stops.

First off, make sure the path to your BDS folder is set correctly.

Run it without the `--rm` so the container doesn't instantly delete itself after is stops. It might still exit straight away, but by removing the `--rm` part, you are still leaving all of the container intact after the main process finishes.

Do `docker ps -a` to list all containers. Your container should be in there somewhere.

Once you found it, run `docker exec -it <container name> /bin/bash` to enter the container's shell. It's almost like SSH, but you're entering the container instead of a different computer. From here, navigate your way to `/data` just like you would any other computer. Verify the correct files are indeed in `/data`. If they aren't, well your volume path is set wrong.

While you are connected to the container's shell, you could also run the EZ normally. Ie. as you would without docker. See [the wiki](https://github.com/Element-0/ElementZero/wiki/Install-and-run-in-linux). You can skip steps 3 and 4 as you already have the relevant files.
