### ISSUE TITLE
How can i get to know IP address of server

### ISSUE THREAD

**Issue by Tetroner9** [codehz/ElementZero#131]
I just installed and ran the server and i followed all instructions and the server just runs fine. But how can i get ip address of the server i tried with my own ip but still doesnt work

**Comment by Weissnix4711** [comment]
The public IP? Search Google for "what is my ip?" or have a look on your router's admin panel. It'll be in there too.

Also, you will need to set up port forwarding if you want to access the server outside of your private network.

Every router is different, so how you set up port forwarding will depend on your router. It's usually under NAT in the web panel.

**Comment by thecrafterjt** [comment]
Hi, if he runs the server on the same machine as the game (Win10) he will need to exempt the Minecraft client from UWP loopback restrictions:
`CheckNetIsolation.exe LoopbackExempt –a –p=S-1-15-2-1958404141-86561845-1752920682-3514627264-368642714-62675701-733520436`
In order to play locally. Then try to join 127.0.0.1
If you run the server on a different machine than the game: try "ifconfig" for Linux and "ipconfig" for Windows based oss.
Btw. @Weissnix4711 then do you think, i will get a reply on my issue? I know its not a bug and shouldn't have high priority, but you know... :)

**Comment by Weissnix4711** [comment]
On most Linux distros, you'll need to use `ip a` instead of `ifconfig`.

About your issue, @thecrafterjt I would help, but I'm not good at making plugins. I mostly stick to the Scripting API.

**Comment by madeofstown** [comment]
If you are running from a Windows PC you will need to open ports for BDS/EZ on the windows firewall. Google how to do it. Then you also need to go to your router settings website and open a port and also forward it. Look for NAT or port forwarding settings. You need to forward the port to the machine that is running BDS. If you still can't connect to your server from outside your home network then you probably have another firewall somewhere. Use canyouseeme.org to check if your machine is firewalled.
