### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by SurvivalGuy52** [codehz/ElementZero#172]
I see that running Minecraft with wine is an option but I’m missing a few things not sure what.
What’s packages do I to get Minecraft running on wine?

**Comment by elijahr2411** [comment]
Are you talking about running ElementZero, or Minecraft itself?

**Comment by SurvivalGuy52** [comment]
I mean for the Minecraft bedrock dedicated server software. And also while we are at for a server with elementzero.

**Comment by elijahr2411** [comment]
The regular Bedrock Dedicated Server software cannot be run under wine because it uses windows-only dlls and is restricted in code to Windows 10. However, ElementZero **can** be run under wine. (As well as supporting plugins)

The recommended method to install ElementZero is Docker, which is actually really easy to install. We have a guide for a Docker install [here](https://element-0.github.io/ElementZero.wiki/linux-install-docker) which includes links to a more noob-friendly guide and even a shell script that auto-installs it for you.

However, you can also install it directly through wine, without docker. For this, you'll need the VCRUNTIME140.DLL from a windows 10 computer. We have a guide for that [here](https://element-0.github.io/ElementZero.wiki/linux-install-no-docker)

**Comment by SurvivalGuy52** [comment]
Got you, thanks for the help.

**Comment by elijahr2411** [comment]
Of course!

**Comment by Weissnix4711** [comment]
Note: you might be able to install vc redist 2015-2019 from winetricks. Or copy from a Windows machine / internet, or maybe even try downloading the installer from microsoft's website and running that.

Note: The installer will require a desktop environment. If you're installing this on a headless server, just copy the files from another machine.
